language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
notifications:
  email: false
before_script:
  - yarn
script:
  - yarn test:lcov__MOCHA____ISTANBUL__
  - yarn check-coverage__ISTANBUL__
  - yarn build
after_success:
  - yarn report-coverage__CODECOV__